apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sboot
  name: sboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sboot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sboot
    spec:
      containers:
      - image: aklot07/sboot:1.0
        name: sboot
        ports:
        - containerPort: 8091
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sboot
  name: sboot
spec:
  ports:
  - name: 8090-8080
    port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: sboot
  type: NodePort
status:
  loadBalancer: {}
